name: macOS

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    concurrency:
      group: macos-setup
      cancel-in-progress: true
    steps:
      - name: Setup
        run: curl -sL https://mie998.github.io/dotfiles/install.sh | sh
