name: Pages

on: [push]

jobs:
  pages:
    name: Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - run: mkdir -p out
      - run: cp -f install.sh out/

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
        if: github.ref == 'refs/heads/main'
